spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyvenue
spring.datasource.username=postgres
spring.datasource.password=Remya@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
